language: node_js
node_js:
- '4'
script:
- npm run test:cov
after_script:
- if [[ `node --version` == *v4* ]]; then cat ./coverage/lcov.info | ./node_modules/.bin/codeclimate-test-reporter;
  fi
env:
  global:
    secure: RHDW4AgP/KHsYfhOn0bKVMPHhTefbLpMT0v3nUF2HtuT8WuBJ085F4bAYkTOEDsZt/N/x9h57N+4Wli1/hT1S1Dojr3PsSZntwlsHq9ECPHlHQ2R5jgJ+10qgIJGEJX2g2PXnWSnTDsqrnnCO0rczmKU3P9uoQMg7ruMFeQ+H+6V17U1CFMqBE8k5lEh/Du6172KD9a9+90+m5Om/pw7xlLNMyTpK3Pi64pbgVZu4+7s0BYzc7sgKQgY/OysZGHK5/ptVel4Kux9+e8wRJ0NyTfVvysX/fftIu/z0oCA+k5ZoPxChb2e46m/CgKqpivlFJwi1KCbVxeZ3Q9QRJpQ3EjmnxGzc9Qc7pQUYz3qPWi7z/NlZ5SbegWKqqECPOwX96nQC/n27xgQnvCbX8eZAB6P+7mxQqoQEYT93W9b9q9sBp+TlrPwqJn1n9xtbRfUckVdsNjl9UQ9LCh+vSP9R2oOZwLAb28g8vyg88I/n8qmSQi9RKrtYDrw5WaFWggGE3XLphGIll4rnr+qsV3RpcZoSE6k1z8+CvSm1rJ1aR7P2WwWSz6YzRy9MEMlyBZvFmDVYV75LVx/GdCuiLdFoOqrx3h3nDcvP3o3aJIR+WgM4S2LMQLEd/fn8/DoUZgTfzACdq2Gw2wae78gnJO80PG325lV8o5Tvk81B+cE7eA=
